import { type ArgumentsHost, Catch, type ExceptionFilter, HttpStatus } from "@nestjs/common";
import type { Response } from "express";
import { DomainError } from "../../../../shared-kernel/domain-error";
import type { RequestWithId } from "../../../../shared-kernel/request-id.middleware";

const STATUS_BY_CODE: Record<string, number> = {
  // Erreurs cross-module déléguées à Tenders/Client Portfolio/Generation/Export/Pricing/Validation
  // — mêmes codes que leurs propres error filters (même motif qu'ExportErrorFilter, Sprint 8A).
  TENDER_NOT_FOUND: HttpStatus.NOT_FOUND,
  TENDER_PERMISSION_MISSING: HttpStatus.FORBIDDEN,
  CLIENT_ACCOUNT_NOT_FOUND: HttpStatus.NOT_FOUND,
  CLIENT_ACCOUNT_ARCHIVED: HttpStatus.CONFLICT,
  CLIENT_PERMISSION_MISSING: HttpStatus.FORBIDDEN,
  GENERATION_NOT_FOUND: HttpStatus.NOT_FOUND,
  GENERATION_ALREADY_RUNNING: HttpStatus.CONFLICT,
  PROMPT_TEMPLATE_NOT_FOUND: HttpStatus.UNPROCESSABLE_ENTITY,
  NO_ACTIVE_PROMPT_VERSION: HttpStatus.UNPROCESSABLE_ENTITY,
  PRICING_ESTIMATE_NOT_FOUND: HttpStatus.NOT_FOUND,
  PRICING_ESTIMATE_VERSION_NOT_FOUND: HttpStatus.NOT_FOUND,
  VALIDATION_RUN_NOT_FOUND: HttpStatus.NOT_FOUND,
  EXPORT_TEMPLATE_NOT_FOUND: HttpStatus.UNPROCESSABLE_ENTITY,
  NO_ACTIVE_EXPORT_TEMPLATE_VERSION: HttpStatus.UNPROCESSABLE_ENTITY,
  EXPORT_BLOCKED: HttpStatus.UNPROCESSABLE_ENTITY,
  INVALID_SECTION_SELECTION: HttpStatus.UNPROCESSABLE_ENTITY,
  CROSS_CLIENT_CONTENT: HttpStatus.FORBIDDEN,

  DELIVERABLE_NOT_FOUND: HttpStatus.NOT_FOUND,
  DUPLICATE_DELIVERABLE: HttpStatus.CONFLICT,
  DELIVERABLE_SECTION_NOT_FOUND: HttpStatus.NOT_FOUND,
  DUPLICATE_DELIVERABLE_SECTION: HttpStatus.CONFLICT,
  DELIVERABLE_SECTION_LOCKED: HttpStatus.CONFLICT,
  DELIVERABLE_REVISION_NOT_FOUND: HttpStatus.NOT_FOUND,
  IMMUTABLE_DELIVERABLE_REVISION: HttpStatus.CONFLICT,
  DELIVERABLE_REVISION_EDIT_CONFLICT: HttpStatus.CONFLICT,
  INVALID_DELIVERABLE_REVISION_STATUS_TRANSITION: HttpStatus.CONFLICT,
  DELIVERABLE_REVISION_NOT_VALIDATED_FOR_EXPORT: HttpStatus.UNPROCESSABLE_ENTITY,
  DELIVERABLE_REVIEW_REQUIRES_READY_REVISION: HttpStatus.CONFLICT,
  DELIVERABLE_COMMENT_NOT_FOUND: HttpStatus.NOT_FOUND,
  DELIVERABLE_COMMENT_ALREADY_RESOLVED: HttpStatus.CONFLICT,
  DELIVERABLE_TEMPLATE_NOT_FOUND: HttpStatus.NOT_FOUND,
  DELIVERABLE_TEMPLATE_VERSION_NOT_FOUND: HttpStatus.NOT_FOUND,
  NO_ACTIVE_DELIVERABLE_TEMPLATE_VERSION: HttpStatus.UNPROCESSABLE_ENTITY,
  INVALID_VERSION_LIFECYCLE_TRANSITION: HttpStatus.CONFLICT,
  DELIVERABLE_TEMPLATE_VERSION_ACTIVATION_CONFLICT: HttpStatus.CONFLICT,
  DOCUMENT_THEME_NOT_FOUND: HttpStatus.NOT_FOUND,
  DOCUMENT_THEME_VERSION_NOT_FOUND: HttpStatus.NOT_FOUND,
  DOCUMENT_THEME_VERSION_ACTIVATION_CONFLICT: HttpStatus.CONFLICT,
  THEME_VERSION_ALREADY_USED_IN_FINAL_EXPORT: HttpStatus.CONFLICT,
  INVALID_DELIVERABLE_TEMPLATE_CONFIG: HttpStatus.UNPROCESSABLE_ENTITY,
  DELIVERABLE_PERMISSION_MISSING: HttpStatus.FORBIDDEN,
  CROSS_CLIENT_DELIVERABLE_CONTENT: HttpStatus.FORBIDDEN,
  COMPLIANCE_MATRIX_ENTRY_NOT_FOUND: HttpStatus.NOT_FOUND,
  CHECKLIST_PIECE_ENTRY_NOT_FOUND: HttpStatus.NOT_FOUND,
  DELIVERABLE_ANNEX_NOT_FOUND: HttpStatus.NOT_FOUND,
  UNSUPPORTED_READ_ONLY_DELIVERABLE: HttpStatus.UNPROCESSABLE_ENTITY,
  SECTION_TASK_TYPE_NOT_CONFIGURED: HttpStatus.UNPROCESSABLE_ENTITY,
  GENERATION_NOT_USABLE_FOR_REVISION: HttpStatus.UNPROCESSABLE_ENTITY,
  DELIVERABLE_NOT_READY_FOR_APPROVAL: HttpStatus.UNPROCESSABLE_ENTITY,
  DELIVERABLE_COST_REPORT_ALREADY_FROZEN: HttpStatus.CONFLICT,
  DOCUMENT_NOT_FOUND: HttpStatus.NOT_FOUND,
  DOCUMENT_NOT_USABLE_FOR_DELIVERABLE: HttpStatus.UNPROCESSABLE_ENTITY,
  SYSTEM_SCOPE_NOT_TENANT_CREATABLE: HttpStatus.FORBIDDEN,
};

@Catch(DomainError)
export class DeliverableErrorFilter implements ExceptionFilter {
  catch(exception: DomainError, host: ArgumentsHost): void {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<Response>();
    const request = ctx.getRequest<RequestWithId>();
    const status = STATUS_BY_CODE[exception.code] ?? HttpStatus.INTERNAL_SERVER_ERROR;

    response.status(status).json({
      error: { code: exception.code, message: exception.message, requestId: request.id },
    });
  }
}
