import { Prisma, type Generation as GenerationRecord } from "@prisma/client";
import { Generation } from "../domain/generation.aggregate";
import type { GenerationStatus } from "../domain/generation-status";
import type { GenerationTaskType } from "../domain/generation-task-type";

export function toDomain(record: GenerationRecord): Generation {
  return Generation.rehydrate({
    id: record.id,
    organizationId: record.organizationId,
    clientAccountId: record.clientAccountId,
    tenderId: record.tenderId,
    taskType: record.taskType as GenerationTaskType,
    targetRef: record.targetRef ?? undefined,
    parentGenerationId: record.parentGenerationId ?? undefined,
    rootGenerationId: record.rootGenerationId,
    version: record.version,
    status: record.status as GenerationStatus,
    attemptCount: record.attemptCount,
    promptTemplateId: record.promptTemplateId,
    promptVersionId: record.promptVersionId,
    promptVersionNumber: record.promptVersionNumber,
    routingPolicyId: record.routingPolicyId ?? undefined,
    routingPolicyVersion: record.routingPolicyVersion ?? undefined,
    routingDecisionId: record.routingDecisionId ?? undefined,
    modelProvider: record.modelProvider ?? undefined,
    modelKey: record.modelKey ?? undefined,
    fallbackLevel: record.fallbackLevel,
    generatedContent: record.generatedContent ?? undefined,
    structuredContent: record.structuredContent ?? undefined,
    editedContent: record.editedContent ?? undefined,
    editedStructuredContent: record.editedStructuredContent ?? undefined,
    editedBy: record.editedBy ?? undefined,
    editedAt: record.editedAt ?? undefined,
    inputTokenCount: record.inputTokenCount ?? undefined,
    outputTokenCount: record.outputTokenCount ?? undefined,
    totalTokenCount: record.totalTokenCount ?? undefined,
    estimatedCostAmount: record.estimatedCostAmount ? record.estimatedCostAmount.toString() : undefined,
    currency: record.currency ?? undefined,
    latencyMs: record.latencyMs ?? undefined,
    errorCode: record.errorCode ?? undefined,
    errorMessage: record.errorMessage ?? undefined,
    createdBy: record.createdBy,
    createdByRole: record.createdByRole ?? undefined,
    createdAt: record.createdAt,
    completedAt: record.completedAt ?? undefined,
    validatedBy: record.validatedBy ?? undefined,
    validatedAt: record.validatedAt ?? undefined,
    rejectedBy: record.rejectedBy ?? undefined,
    rejectedAt: record.rejectedAt ?? undefined,
    rejectionReason: record.rejectionReason ?? undefined,
  });
}

export function toPersistence(generation: Generation) {
  return {
    id: generation.id,
    organizationId: generation.organizationId,
    clientAccountId: generation.clientAccountId,
    tenderId: generation.tenderId,
    taskType: generation.taskType,
    targetRef: generation.targetRef ?? null,
    parentGenerationId: generation.parentGenerationId ?? null,
    rootGenerationId: generation.rootGenerationId,
    version: generation.version,
    status: generation.status,
    attemptCount: generation.attemptCount,
    promptTemplateId: generation.promptTemplateId,
    promptVersionId: generation.promptVersionId,
    promptVersionNumber: generation.promptVersionNumber,
    routingPolicyId: generation.routingPolicyId ?? null,
    routingPolicyVersion: generation.routingPolicyVersion ?? null,
    routingDecisionId: generation.routingDecisionId ?? null,
    modelProvider: generation.modelProvider ?? null,
    modelKey: generation.modelKey ?? null,
    fallbackLevel: generation.fallbackLevel,
    generatedContent: generation.generatedContent ?? null,
    structuredContent:
      generation.structuredContent === undefined ? Prisma.DbNull : (generation.structuredContent as Prisma.InputJsonValue),
    editedContent: generation.editedContent ?? null,
    editedStructuredContent:
      generation.editedStructuredContent === undefined ? Prisma.DbNull : (generation.editedStructuredContent as Prisma.InputJsonValue),
    editedBy: generation.editedBy ?? null,
    editedAt: generation.editedAt ?? null,
    inputTokenCount: generation.inputTokenCount ?? null,
    outputTokenCount: generation.outputTokenCount ?? null,
    totalTokenCount: generation.totalTokenCount ?? null,
    estimatedCostAmount: generation.estimatedCostAmount ?? null,
    currency: generation.currency ?? null,
    latencyMs: generation.latencyMs ?? null,
    errorCode: generation.errorCode ?? null,
    errorMessage: generation.errorMessage ?? null,
    createdBy: generation.createdBy,
    createdByRole: generation.createdByRole ?? null,
    createdAt: generation.createdAt,
    completedAt: generation.completedAt ?? null,
    validatedBy: generation.validatedBy ?? null,
    validatedAt: generation.validatedAt ?? null,
    rejectedBy: generation.rejectedBy ?? null,
    rejectedAt: generation.rejectedAt ?? null,
    rejectionReason: generation.rejectionReason ?? null,
  };
}
